name: Deploy

on:
  push:
    branches:
      - master

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: golang:1.17.3
    services:
      db:
        image: postgres:14-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: captcha
      cache:
        image: redis:6-alpine
        ports:
          - 6379:6379
      mongo:
        image: mongo:5-focal
        restart: always
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: captcha
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Installling dependencies
        run: go mod download

      - name: Build
        run: go build main.go

      - name: Run test & coverage
        run: go test -v -coverprofile=coverage.out -covermode=atomic ./...
        env:
          ENVIRONMENT: development
          DATABASE_URL: postgres://postgres:password@db:5432/captcha?sslmode=disable
          REDIS_URL: redis://@cache:6379/
          MONGO_URL: mongodb://root:password@mongo:27017/CAPTCHA?useNewUrlParser=true&useUnifiedTopology=true&authSource=admin
          MONGO_DBNAME: captcha
          TZ: UTC

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: go

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

      - uses: codecov/codecov-action@v2

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: 'deploy --build-arg CERT_URL=${{ secrets.CERT_URL }}'

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          set_commits: skip
          version: ${{ github.sha }}
